# NAME: Kevin Li
# EMAIL: li.kevin512@gmail.com
# ID: 123456789

SOURCES=my_beaglebone.jpg connected.png copy.png build_run.png git.png
TAR=lab4a-123456789.tar.gz

dist:
	tar -cvzf $(TAR) $(SOURCES) Makefile README

clean:
	rm -f $(TAR)